### ISSUE TITLE
Could I export the result into a report file?

### ISSUE THREAD

**Issue by minhtruong92** [codacy/codacy-phpmd#12]
Hi team,

I have recently pulled codacy-phpmd docker image, after completed the prerequisite as document mentioned, I run the following command:
docker run -it -v $PWD:/src codacy/codacy-phpmd

I got output from console, I wonder if we can export the result into somewhere to keep tracking.

**Comment by rtfpessoa** [comment]
@minhtruong92 this docker is mainly for Codacy related usage and it is meant to work with a very strict API: `Input: /src and /src/.codacy.json | Output: One result per line`.
You can check https://github.com/codacy/codacy-analysis-cli but keep in mind it is still under development.
